In [1]:
import numpy as np

# Basic Array creation

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4,3.5,"Hii"]
a

[1, 2, 3, 4, 3.5, 'Hii']

In [8]:
np.array(a)  # here all get converted into strings

array(['1', '2', '3', '4', '3.5', 'Hii'], dtype='<U32')

In [10]:
# here i wil not give strings

b = [3,4.5,6.7]


In [12]:
np.array(b) # all get converted itno float , even int 

array([3. , 4.5, 6.7])

In [13]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [16]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
# generate some zeros
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [21]:
# generate zeros as a matrix
arr = np.zeros((7,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr = np.ones((8,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr = np.linspace(1,20,4)  # equally space distribution
arr

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [29]:
arr = np.linspace(0,1,100)  #it means between 0 and 1 i need 100 elements , and bw them 
arr                          # space are equally distributed

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# Random Generation function

In [30]:
# random number generation

# we will use random library

np.random.rand(20)

array([0.05160967, 0.23593941, 0.86340499, 0.92515548, 0.55147878,
       0.74726037, 0.79435486, 0.32785131, 0.75678892, 0.28787447,
       0.50480743, 0.32949628, 0.94100088, 0.79856263, 0.65565462,
       0.25583808, 0.80313758, 0.13751945, 0.88110038, 0.48831401])

In [32]:
# note = its a vector bcz it open and closes bw one bracket = [] , 
# and if its [[]] then it is a matrix

In [35]:
# when a value comes bw 0 and 1 its called normalization
# and when a value comes bw -3 and 3 its called standardization

In [36]:
np.random.randn(20)    # its standardization

array([ 0.58810878, -0.09559724, -0.62683574,  0.12179346, -0.21425571,
       -0.00549069,  0.83302467, -1.75023457, -1.32934099,  1.2031821 ,
       -0.03706739, -0.13042241,  0.26917117,  0.59787844, -0.37448283,
        1.8952953 ,  0.45725513, -0.96456756, -0.82112245,  0.31322692])

In [38]:
# generate random numbers or integera
np.random.randint(20)   # generated random no between 0 and 20

18

In [43]:
np.random.randint(5,50,10) # 10 random no generated bw 5 and 50

array([18, 16, 36, 30, 19, 45, 31, 49, 39, 14], dtype=int32)

# Array Attributes

In [47]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [48]:
# shape attribute
arr.shape 

(3, 3)

In [49]:
# size , means total element
arr.size

9

In [50]:
# check type
arr.dtype

dtype('int64')

# Array Methods

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
# to find minimum elements
arr.min()

np.int64(1)

In [61]:
arr.max()

np.int64(9)

In [63]:
# sum , sum of all elements
arr.sum()

np.int64(45)

In [65]:
# sum of what i want , any row or column
np.sum(arr,axis = 0)  # horizontal called 1

array([12, 15, 18])

In [66]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [69]:
# find mean  , means middle number
arr.mean()

np.float64(5.0)

In [70]:
# standard deviation
arr.std()

np.float64(2.581988897471611)

In [71]:
# maximum element index 
arr.argmax()

np.int64(8)

In [72]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [75]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [76]:
# now its a vector , now convert it into matrix

In [78]:
# reshape
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])