In [1]:
import numpy as np

# Basic Array creation

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
a = [1,2,3,4,3.5,"Hii"]
a

[1, 2, 3, 4, 3.5, 'Hii']

In [5]:
np.array(a)  # here all get converted into strings

array(['1', '2', '3', '4', '3.5', 'Hii'], dtype='<U32')

In [6]:
# here i wil not give strings

b = [3,4.5,6.7]


In [7]:
np.array(b) # all get converted itno float , even int 

array([3. , 4.5, 6.7])

In [8]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
# generate some zeros
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
# generate zeros as a matrix
arr = np.zeros((7,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr = np.ones((8,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,20,4)  # equally space distribution
arr

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [16]:
arr = np.linspace(0,1,100)  #it means between 0 and 1 i need 100 elements , and bw them 
arr                          # space are equally distributed

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# Random Generation function

In [17]:
# random number generation

# we will use random library

np.random.rand(20)

array([7.36922992e-01, 2.85241366e-01, 2.34483424e-01, 4.23651694e-01,
       2.38532074e-01, 6.72932954e-01, 6.40670936e-01, 9.29486569e-01,
       5.89969360e-01, 9.37776356e-01, 9.41007470e-01, 5.27321069e-01,
       9.12476316e-01, 4.15847990e-01, 5.75653770e-04, 7.03987382e-01,
       9.92885934e-01, 5.54908958e-01, 2.33237558e-02, 4.79513794e-01])

In [18]:
# note = its a vector bcz it open and closes bw one bracket = [] , 
# and if its [[]] then it is a matrix

In [19]:
# when a value comes bw 0 and 1 its called normalization
# and when a value comes bw -3 and 3 its called standardization

In [20]:
np.random.randn(20)    # its standardization

array([-1.11370889,  0.39117522, -0.6801674 ,  0.43342817,  0.29629168,
        0.0377987 ,  0.80675224, -2.08536188, -0.98635592, -0.6272914 ,
       -0.5899039 , -0.65649792,  0.03392357,  0.98048367, -0.67679294,
       -0.0317583 , -1.17900215, -1.54411174,  1.08301435,  0.47075283])

In [21]:
# generate random numbers or integera
np.random.randint(20)   # generated random no between 0 and 20

8

In [22]:
np.random.randint(5,50,10) # 10 random no generated bw 5 and 50

array([14, 41, 21, 46, 15, 37, 17, 21, 49, 46], dtype=int32)

# Array Attributes

In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
# shape attribute
arr.shape 

(3, 3)

In [25]:
# size , means total element
arr.size

9

In [26]:
# check type
arr.dtype

dtype('int64')

# Array Methods

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# to find minimum elements
arr.min()

np.int64(1)

In [29]:
arr.max()

np.int64(9)

In [30]:
# sum , sum of all elements
arr.sum()

np.int64(45)

In [31]:
# sum of what i want , any row or column
np.sum(arr,axis = 0)  # horizontal called 1

array([12, 15, 18])

In [32]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [33]:
# find mean  , means middle number
arr.mean()

np.float64(5.0)

In [34]:
# standard deviation
arr.std()

np.float64(2.581988897471611)

In [35]:
# maximum element index 
arr.argmax()

np.int64(8)

In [36]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [37]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
# now its a vector , now convert it into matrix

In [39]:
# reshape
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# Numpy indexing and Slicing of Vectors

In [40]:
import numpy as np

In [41]:
arr = np .arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
# indexing

In [43]:
arr[2:6]

array([13, 14, 15, 16])

In [44]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [45]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
arr[9:]

array([20])

# Indexing and Slicing of a matrix

In [47]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [48]:
arr[3]

array([16, 17, 18, 19, 20])

In [49]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [50]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [51]:
arr[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [52]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [53]:
arr[2:5:2,2:5:2]

array([[13, 15],
       [23, 25]])

In [54]:
arr =np.arange(1,73).reshape(9,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71, 72]])

In [55]:
# needs 1,8 and 65,72
arr[::7,::7]

array([[ 1,  8],
       [57, 64]])

In [56]:
# needs 30,32 and 54,56    
arr[3:7:3,5:8:2]   

array([[30, 32],
       [54, 56]])

In [57]:
# needs 27,31 and 51,55
arr[3:7:3,2:7:4] # 3=starting,7=last+1,3=next from starting count upto where u want gap 

array([[27, 31],
       [51, 55]])

# Boolean Indexing

In [58]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
bool_index = arr%2 ==0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [60]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# Array Operation

In [61]:
import numpy as np

In [62]:
# Arthmetic operation

a1 = np.array([1,2,3,4,5])  
a2 = np.array([6,7,8,9,10])

In [63]:
a1 + a2        # size of the both array should be same for this 

array([ 7,  9, 11, 13, 15])

In [64]:
a2 - a1

array([5, 5, 5, 5, 5])

In [65]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [66]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [67]:
a1 // a2

array([0, 0, 0, 0, 0])

In [68]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [69]:
l = [10,20,30,40]
arr = np.array(l)

In [70]:
for i in l:
    print(i+10)

20
30
40
50


In [71]:
arr+10

array([20, 30, 40, 50])

# Mathematical operations in matrix

In [72]:
arr2 = np.arange(1,26).reshape(5,5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [73]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [74]:
arr2 * 10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [75]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# Deep and Shallow Copy

In [77]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
slice = a[0:5]
slice

array([1, 2, 3, 4, 5])

In [79]:
# now we will broadcasting in this slicing

slice = a[0:5]
slice =  slice * 10

slice

array([10, 20, 30, 40, 50])

In [80]:
# we have done operation in a sliced portion , but original will not change 

a  # but in list it get changed , here in array it will not change

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [81]:
a[4:6]* 10

array([50, 60])

In [82]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
a 
b = a

In [84]:
b[1] = 99
b  # it get changed

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
# if i want that if change somehting in b , in a nothing will get changed

b = a.copy()


In [86]:
b[0] = 55

In [87]:
b

array([55, 99,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
a

array([ 1, 99,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
# 1:18:11

# matrix operation

In [90]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [91]:
A

array([[1, 2],
       [3, 4]])

In [92]:
B

array([[5, 6],
       [7, 8]])

In [93]:
A * B

array([[ 5, 12],
       [21, 32]])

In [94]:
A @ B # real multiply of a matrix

array([[19, 22],
       [43, 50]])

In [95]:
# or 
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [96]:
# transpose of a matrix
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

In [97]:
A

array([[1, 2],
       [3, 4]])

In [98]:
B

array([[5, 6],
       [7, 8]])

In [99]:
# stacking Array , and in this use vectors , u cant use matrix

In [100]:
# u cant stack two matrix , u can stact two arrays or vector

In [101]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [102]:
np.vstack((a,b))  # it gets vertically alligned

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
np.hstack((a,b)) # it gets horizontally aligned , stacked

array([1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Spliting Array

In [105]:
c = np.arange(16).reshape(4,4)
c


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.hsplit(c,2)   # this can split it into two parts , and 2 means in two parts

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [107]:
np.hsplit(c,2)   

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [108]:
# u cant divide it into 3 parts , bcz it has not equal sitribution for 3
np.hsplit(c,3)


ValueError: array split does not result in an equal division

In [ ]:
np.hsplit(c,4)

In [ ]:
# vertical split
a = np.vsplit(c,4)
a

In [ ]:
for i in a:
    print(i)
    

In [ ]:
# it get splitted into 2d matrix


# Excercise

In [ ]:
# valid sudok

In [1]:
import numpy as np

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
np.sum(s , axis = 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [4]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
z = np.sum(s,axis=0)
m = np.sum(s,axis=1)

if np.all(z == 45) and np.all(m == 45):
    print("all rows and columns have sum 45")
else:
    print("Invalid Sudoku")

all rows and columns have sum 45


In [6]:
valid = True

for row in s:
    for element in row:
        if not(1<=element <=9):
            valid = False

if valid:
    print("all numbers are in bw 1 and 9")
else:
    print("numbers are upper than 9")


all numbers are in bw 1 and 9


In [7]:
np.sum(s,axis = 0) # 0 for columns


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [8]:
b = np.sum(s,axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
c = np.sum(s,axis=1)   # this was for rows
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [10]:
d = np.sum(s,axis=0)    # for columns
for i in d:
    if i != 45:
        print("sudoko is not valid")
        break
else:
    print("for columns it is valid")

for columns it is valid


In [11]:
 # now check in all of the box for 3*3 matrix , is theresum is 45 or not,

In [12]:
# for this we will use slicing 

In [13]:
g = s[0:3,0:3]
g

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [14]:
#h = g.sum()
if g.sum()== 45:
    print("matrix of 3 by 3 is a valid sudoko")
else:
    print("not valid!")



matrix of 3 by 3 is a valid sudoko


In [15]:
# now for next three 
f = s[0:3,0:3]
j = s[0:3,3:6] 
k = s[0:3,6:]

l = s[3:6,0:3]  # these three are for 1 matix or middle matrix
m = s[3:6,3:6]
n = s[3:6,6:]

o = s[6:,0:3]
p = s[6:,3:6]
q = s[6:,6:]

In [16]:
if f.sum()==45 and j.sum()==45 and k.sum()==45 and l.sum()==45 and m.sum()==45 and n.sum()==45 and o.sum()==45 and p.sum()==45 and q.sum()==45:
    
    print("valid sudoko")
else:
    print("Invalid sudoko")

valid sudoko


In [17]:
# works but upper code looks some boring,
# so do some shortcuts
box = [f,j,k,l,m,n,o,p,q]

if np.all([b.sum() == 45 for b in box]):
    print("Valid sudoko:)")
else:
    print("Invalif sudoko!!")


Valid sudoko:)


In [36]:
# now a shortcut for this 

for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())         #qs ends at 1:44:30
        

45
45
45
45
45
45
45
45
45


In [1]:
# second problem
import numpy as np
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [2]:
# 1.Get the shape of the matrix

#np.shape(data)
#or

data.shape

(5, 3)

In [3]:
#Find the average age of students.
for i in range(0,5):
    #for j in range(0,3):
        f = data[i:i+1]
        print(f.sum()/3)

60.333333333333336
66.33333333333333
62.666666666666664
51.0
65.0


In [4]:
s1 = data[0,0:]
s1.sum()/3

np.float64(60.333333333333336)

In [5]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [6]:
#Extract Math marks of all students.
# middle is math marks
for i in range(0,5):
    #for j in range(0,1):
       print(data[i:i+1,1])


[85]
[92]
[76]
[65]
[90]


In [7]:
data[0:,1]

array([85, 92, 76, 65, 90])

In [8]:
#Find the highest Science mark.
# last column is of ||

data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [9]:
for i in range(0,5):
    l = data[i:i+1,2]
    print(l)
#max_marks = np.max(l,axis=0)
print(max_marks)

[78]
[88]
[95]
[70]
[85]


NameError: name 'max_marks' is not defined

In [10]:
max_marks = data[0,2]

for i in range(0,5):
    l = data[i,2]

    if l > max_marks:
        max_marks = l

print(max_marks)

95


In [11]:
# simple
np.max(data[0:,2])

np.int64(95)

In [12]:
#Get details of the student who scored more than 90 in Math.
data # middle is of maths marks

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [13]:
for i in range(0,5):
    #maxx = data[i:i+1,1]
    maxx = data[i,1]
    if maxx > 90:
        print("Marks greater than 90 is",maxx,"of student",i)
        break
else:
    print("no one gets no greater than 90")


Marks greater than 90 is 92 of student 1


In [14]:
#Increase Math marks of all students by 5.
# middle is of maths marks
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [15]:
for i in range(0,5):
    add = data[i,1] + 5
    print(add)

90
97
81
70
95


In [16]:
#Find how many students are younger than 19.
# first column is age
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [17]:
count = 0
for i in range(0,5):
    age = data[i,0]
    if age < 19:
        count+=1
print(count,"students who are younger than 19 ")

3 students who are younger than 19 


In [18]:
#Calculate the average marks in each subject (column-wise mean)

# Columns: [Age, Math Marks, Science Marks]
#data = np.array([
    #[18, 85, 78],   # Student 1
    #[19, 92, 88],   # Student 2
    #[17, 76, 95],   # Student 3
    #[18, 65, 70],   # Student 4
    #[20, 90, 85]    # Student 5
#])

In [19]:
data[0:,1:]


array([[85, 78],
       [92, 88],
       [76, 95],
       [65, 70],
       [90, 85]])

In [20]:
mathsAvg = np.sum(data[0:,1]/5)
scienceAvg = np.sum(data[0:,2]/5)


In [21]:
mathsAvg

np.float64(81.6)

In [23]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [29]:
math_total = 0
science_total = 0

for i in range(0,5):
    math_total += data[i,1]
    science_total += data[i,2]

math_Avg = math_total/5
science_Avg = science_total/5


print("Average of maths marks = ", math_Avg)
print("Average of science marks = ", science_Avg)

Average of maths marks =  81.6
Average of science marks =  83.2


In [30]:
#Get data of students who scored at least 80 in both subjects.
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [51]:
count = 0

for i in range(0,5):
    if data[i][1] >= 80 and data[i][2] >= 80:
        count += 1

print(count, "students got at least 80 marks")

2 students got at least 80 marks


In [55]:
#Replace all Science marks < 75 with 0.
empty = []
for i in range(0,5):
    if data[i][2] < 75:
        data[i][2] = 0

print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
